
version: "3.9"
services:
  backend:
    build: ./backend
    container_name: ai_backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o
    networks:
      - ai_network

  frontend:
    build: ./frontend
    container_name: ai_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge
